# Generated by Django 2.1 on 2018-08-31 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Atividade')),
            ],
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome da Turma')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome da passo')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome do Aluno')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Classes', verbose_name='Turma')),
            ],
        ),
        migrations.AddField(
            model_name='classes',
            name='step',
            field=models.ManyToManyField(to='app.Step', verbose_name='Passos'),
        ),
        migrations.AddField(
            model_name='activity',
            name='step',
            field=models.ManyToManyField(to='app.Step', verbose_name='Passos'),
        ),
        migrations.AddField(
            model_name='activity',
            name='student',
            field=models.ManyToManyField(to='app.Student', verbose_name='Estudantes'),
        ),
    ]
