# Generated by Django 2.1 on 2018-09-06 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome do Nós')),
            ],
        ),
        migrations.CreateModel(
            name='StudentInformations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True, verbose_name='Nota do Aluno')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Node', verbose_name='Nome do Nós')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Student', verbose_name='Estudantes')),
            ],
        ),
        migrations.RemoveField(
            model_name='activity',
            name='step',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='student',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='step',
        ),
        migrations.DeleteModel(
            name='Step',
        ),
        migrations.AddField(
            model_name='node',
            name='activity',
            field=models.ManyToManyField(to='app.Activity', verbose_name='Atividades'),
        ),
        migrations.AddField(
            model_name='node',
            name='node_children',
            field=models.ManyToManyField(related_name='_node_node_children_+', to='app.Node', verbose_name='Nó Filho'),
        ),
        migrations.AddField(
            model_name='node',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, through='app.StudentInformations', to='app.Student'),
        ),
        migrations.AddField(
            model_name='classes',
            name='node',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Node', verbose_name='Nó raiz'),
        ),
    ]
