# Generated by Django 2.1 on 2018-09-06 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180906_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='node_children',
            field=models.ManyToManyField(blank=True, null=True, related_name='_node_node_children_+', to='app.Node', verbose_name='Nó Filho'),
        ),
    ]
