# Generated by Django 2.1 on 2018-09-07 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180906_0227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='node_source',
        ),
        migrations.AddField(
            model_name='node',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Course', verbose_name='Curso que o nó pertence'),
        ),
    ]
