# Generated by Django 2.1 on 2018-09-07 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180907_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='node_end',
            field=models.BooleanField(blank=True, null=True, verbose_name='Nó fim?'),
        ),
    ]
