# Generated by Django 2.1 on 2018-09-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20180907_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='node_end',
            field=models.BooleanField(default=False, verbose_name='Nó fim (Folha)?'),
        ),
        migrations.AlterField(
            model_name='node',
            name='students',
            field=models.ManyToManyField(through='app.StudentInformations', to='app.Student'),
        ),
    ]
