# Generated by Django 2.1 on 2018-09-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20180909_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='node_start',
            field=models.BooleanField(default=False, verbose_name='Nó inicio'),
        ),
    ]
