# Generated by Django 2.1 on 2018-09-09 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_node_node_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.IntegerField(verbose_name='Nível')),
            ],
        ),
        migrations.AddField(
            model_name='node',
            name='depth',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.Level', verbose_name='Nível'),
        ),
    ]
