# Generated by Django 2.1 on 2018-09-11 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20180909_1625'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='node',
            options={'ordering': ['depth']},
        ),
        migrations.AddField(
            model_name='node',
            name='color_representation',
            field=models.CharField(default='#00FF00', max_length=50, verbose_name='Cor da média dos alunos (hex)'),
        ),
    ]
