# Generated by Django 2.1 on 2018-09-14 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20180911_2213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='node',
            options={},
        ),
        migrations.RemoveField(
            model_name='node',
            name='color_representation',
        ),
        migrations.RemoveField(
            model_name='node',
            name='depth',
        ),
        migrations.DeleteModel(
            name='Level',
        ),
    ]
