# Generated by Django 2.1 on 2018-09-14 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20180914_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinformations',
            name='notes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2, verbose_name='Nota do Aluno'),
        ),
    ]
