# Generated by Django 2.1 on 2018-09-20 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20180914_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='ager',
            field=models.IntegerField(default=0, verbose_name='Idade'),
        ),
        migrations.AddField(
            model_name='student',
            name='civil_status',
            field=models.CharField(choices=[('C', 'Casado'), ('S', 'Solteiro')], default='S', max_length=2, verbose_name='Estado civil'),
        ),
        migrations.AddField(
            model_name='student',
            name='color_blind',
            field=models.BooleanField(default=False, verbose_name='Daltônico'),
        ),
        migrations.AddField(
            model_name='student',
            name='school_origin',
            field=models.CharField(choices=[('PB', 'Pública'), ('PA', 'Particular')], default='PB', max_length=2, verbose_name='Origem Escolar'),
        ),
        migrations.AddField(
            model_name='student',
            name='sex',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminio')], default='M', max_length=2, verbose_name='Sexo'),
        ),
    ]
