# Generated by Django 2.1 on 2018-09-22 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20180920_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinformations',
            name='is_evaluated',
            field=models.BooleanField(default=False, verbose_name='Essa atividade é avaliada?'),
        ),
    ]
