# Generated by Django 2.1 on 2018-09-22 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20180922_0036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='is_evaluated',
            new_name='evaluated',
        ),
    ]
