# Generated by Django 2.1 on 2018-09-22 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20180922_0056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='color_blind',
        ),
    ]
