# Generated by Django 2.1 on 2018-10-16 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20181011_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fim da atividade'),
        ),
        migrations.AddField(
            model_name='activity',
            name='percentage_completed',
            field=models.IntegerField(default=0, verbose_name='Porcentagem concluida'),
        ),
        migrations.AddField(
            model_name='activity',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='inicio da atividade'),
        ),
    ]
