# Generated by Django 2.1 on 2018-10-16 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20181016_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinformations',
            name='end_activity',
            field=models.DateField(blank=True, null=True, verbose_name='Iniciou a atividade'),
        ),
        migrations.AddField(
            model_name='studentinformations',
            name='start_activity',
            field=models.DateField(blank=True, null=True, verbose_name='Iniciou a atividade'),
        ),
    ]
