# Generated by Django 2.1 on 2018-10-16 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20181016_0055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='percentage_completed',
        ),
        migrations.AddField(
            model_name='node',
            name='percentage_completed',
            field=models.IntegerField(default=0, verbose_name='Porcentagem concluida'),
        ),
    ]
