# Generated by Django 2.1 on 2018-10-17 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20181017_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='students',
            field=models.ManyToManyField(to='app.Student', verbose_name='Estudantes'),
        ),
    ]
