# Generated by Django 2.1 on 2018-10-17 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_classes_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='students',
        ),
    ]
