# Generated by Django 2.1 on 2018-10-17 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('app', '0033_remove_teacher_classe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
