# Generated by Django 2.1 on 2018-10-19 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='is_way',
            field=models.BooleanField(default=False, verbose_name='É um caminho válido (bom e/ou ruim)'),
        ),
    ]
