# Generated by Django 2.1 on 2018-10-26 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_node_end_node_conexction'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='avg_access',
            field=models.IntegerField(default=0, verbose_name='Média de Acesso'),
        ),
    ]
